run:
  timeout: 5m
  go: '1.25'
  tests: true
  build-tags:
    - integration

linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - prealloc
    - predeclared
    - asciicheck
    - forbidigo
    - makezero
    - promlinter
    - testpackage

  disable:
    - gochecknoglobals  # We use some global vars for flags
    - godox             # We allow TODO/FIXME comments
    - funlen            # Function length is not a hard limit
    - wsl               # Too strict about whitespace

linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/pkg/errors"
            desc: "Use fmt.Errorf with %w instead"
  
  dupl:
    threshold: 150

  forbidigo:
    forbid:
      - "fmt.Print.*"
      - "panic"
    exclude-godoc-examples: true

  goconst:
    min-len: 2
    min-occurrences: 3

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

  gocyclo:
    min-complexity: 15

  goimports:
    local-prefixes: github.com/fredericrous/homelab/vault-operator

  gomnd:
    settings:
      mnd:
        checks:
          - argument
          - case
          - condition
          - return

  govet:
    check-shadowing: true
    enable-all: true

  lll:
    line-length: 120

  misspell:
    locale: US

  nakedret:
    max-func-lines: 30

  prealloc:
    simple: true
    range-loops: true
    for-loops: true

  revive:
    severity: warning
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf

  staticcheck:
    checks: ["all"]

  stylecheck:
    checks: ["all", "-ST1000", "-ST1003"]
    initialisms: ["ACL", "API", "ASCII", "CPU", "CSS", "DNS", "EOF", "GUID", "HTML", "HTTP", "HTTPS", "ID", "IP", "JSON", "JWT", "QPS", "RAM", "RPC", "SLA", "SMTP", "SQL", "SSH", "TLS", "TTL", "UID", "UI", "UUID", "URI", "URL", "UTF8", "VM", "XML", "YAML"]

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - testpackage

    # Exclude generated files
    - path: zz_generated\.
      linters:
        - goimports
        - goconst

    # Allow unused parameters in interfaces
    - linters:
        - unused
      text: ".*is unused"
      path: ".*\\.go"
      source: "^\\s*\\w+\\s+interface\\s*{"

    # Allow certain patterns
    - linters:
        - stylecheck
      text: "ST1003:"  # Allow underscores in test names

  exclude-use-default: false