name: Post Release Tasks

on:
  release:
    types: [published]

jobs:
  trigger-chart-update:
    name: Trigger Chart Update
    runs-on: ubuntu-latest
    steps:
      - name: Check for required secrets
        run: |
          if [ -z "${{ secrets.CHARTS_REPO_TOKEN }}" ]; then
            echo "::error::CHARTS_REPO_TOKEN secret is not set. Please add it to repository secrets."
            exit 1
          fi
          echo "CHARTS_REPO_TOKEN is configured ✓"
      
      - name: Trigger Helm Chart Update Workflow
        run: |
          # Extract version from release tag
          VERSION="${{ github.event.release.tag_name }}"
          
          echo "Triggering Helm chart update for version ${VERSION}"
          
          # Trigger workflow using GitHub API
          RESPONSE=$(curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.CHARTS_REPO_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/update-helm-chart.yaml/dispatches \
            -d "{\"ref\":\"main\",\"inputs\":{\"version\":\"${VERSION#v}\",\"bump_chart_version\":\"true\"}}" \
            -w "\nHTTP_STATUS:%{http_code}" \
            -s)
          
          HTTP_STATUS=$(echo "$RESPONSE" | grep -o "HTTP_STATUS:[0-9]*" | cut -d: -f2)
          BODY=$(echo "$RESPONSE" | sed -n '1,/HTTP_STATUS:/p' | sed '$d')
          
          if [ "$HTTP_STATUS" != "204" ]; then
            echo "::error::Failed to trigger workflow. HTTP Status: $HTTP_STATUS"
            echo "::error::Response: $BODY"
            exit 1
          fi
          
          echo "✅ Successfully triggered Helm chart update for version ${VERSION}"

      # Alternative: Directly trigger using PAT if you prefer
      - name: Alternative - Direct Repository Dispatch
        if: false  # Enable this if the above doesn't work
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.CHARTS_REPO_TOKEN }}  # Use PAT instead of GITHUB_TOKEN
          repository: ${{ github.repository }}
          event-type: helm-chart-update
          client-payload: '{"version": "${{ github.event.release.tag_name }}"}'