name: Post Release Tasks

on:
  release:
    types: [published]

jobs:
  trigger-chart-update:
    name: Trigger Chart Update
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Helm Chart Update Workflow
        run: |
          # Extract version from release tag
          VERSION="${{ github.event.release.tag_name }}"
          
          # Trigger workflow using GitHub API
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.CHARTS_REPO_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/update-helm-chart.yaml/dispatches \
            -d "{\"ref\":\"main\",\"inputs\":{\"version\":\"${VERSION#v}\",\"bump_chart_version\":\"true\"}}"
          
          echo "Triggered Helm chart update for version ${VERSION}"

      # Alternative: Directly trigger using PAT if you prefer
      - name: Alternative - Direct Repository Dispatch
        if: false  # Enable this if the above doesn't work
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.CHARTS_REPO_TOKEN }}  # Use PAT instead of GITHUB_TOKEN
          repository: ${{ github.repository }}
          event-type: helm-chart-update
          client-payload: '{"version": "${{ github.event.release.tag_name }}"}'