name: Test Release Trigger

on:
  release:
    types: [published, created, edited]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Event
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Action: ${{ github.action }}"
          echo "Release Tag: ${{ github.event.release.tag_name }}"
          echo "Release Name: ${{ github.event.release.name }}"
          echo "Is Prerelease: ${{ github.event.release.prerelease }}"
          echo "Is Draft: ${{ github.event.release.draft }}"